#include "fillgridwindow.h"
#include "ui_fillgridwindow.h"

/*----------------------------------------------------------------------------------*/
void FillGridWindow::LinkSquareMap()
{

    Square.insert(std::pair<QString,QGridSquare *>("A1",ui->A1));
    ui->A1->setToolTip("A1");
    ui->A1->GreenSquareClickedTracking = false;
    //QObject::connect(ui->A1, &QGridSquare::RandomButtonEnableSig, this, &FillGridWindow::RandomButtonEnableSlot);
    Square.insert(std::pair<QString,QGridSquare *>("A2",ui->A2));
    ui->A2->setToolTip("A2");
    ui->A2->GreenSquareClickedTracking = false;
    //QObject::connect(ui->A2, &QGridSquare::RandomButtonEnableSig, this, &FillGridWindow::RandomButtonEnableSlot);
    Square.insert(std::pair<QString,QGridSquare *>("A3",ui->A3));
    ui->A3->setToolTip("A3");
    ui->A3->GreenSquareClickedTracking = false;
    //QObject::connect(ui->A3, &QGridSquare::RandomButtonEnableSig, this, &FillGridWindow::RandomButtonEnableSlot);
    Square.insert(std::pair<QString,QGridSquare *>("A4",ui->A4));
    ui->A4->setToolTip("A4");
    //QObject::connect(ui->A4, &QGridSquare::RandomButtonEnableSig, this, &FillGridWindow::RandomButtonEnableSlot);
    ui->A4->GreenSquareClickedTracking = false;
    Square.insert(std::pair<QString,QGridSquare *>("A5",ui->A5));
    ui->A5->setToolTip("A5");
    ui->A5->GreenSquareClickedTracking = false;
    //QObject::connect(ui->A5, &QGridSquare::RandomButtonEnableSig, this, &FillGridWindow::RandomButtonEnableSlot);
    Square.insert(std::pair<QString,QGridSquare *>("A6",ui->A6));
    ui->A6->setToolTip("A6");
    ui->A6->GreenSquareClickedTracking = false;
    //QObject::connect(ui->A6, &QGridSquare::RandomButtonEnableSig, this, &FillGridWindow::RandomButtonEnableSlot);
    Square.insert(std::pair<QString,QGridSquare *>("A7",ui->A7));
    ui->A7->setToolTip("A7");
    ui->A7->GreenSquareClickedTracking = false;
    //QObject::connect(ui->A7, &QGridSquare::RandomButtonEnableSig, this, &FillGridWindow::RandomButtonEnableSlot);
    Square.insert(std::pair<QString,QGridSquare *>("A8",ui->A8));
    ui->A8->setToolTip("A8");
    ui->A8->GreenSquareClickedTracking = false;
    //QObject::connect(ui->A8, &QGridSquare::RandomButtonEnableSig, this, &FillGridWindow::RandomButtonEnableSlot);
    Square.insert(std::pair<QString,QGridSquare *>("A9",ui->A9));
    ui->A9->setToolTip("A9");
    ui->A9->GreenSquareClickedTracking = false;
    //QObject::connect(ui->A9, &QGridSquare::RandomButtonEnableSig, this, &FillGridWindow::RandomButtonEnableSlot);
    Square.insert(std::pair<QString,QGridSquare *>("A10",ui->A10));
    ui->A10->setToolTip("A10");
    ui->A10->GreenSquareClickedTracking = false;
    //QObject::connect(ui->A10, &QGridSquare::RandomButtonEnableSig, this, &FillGridWindow::RandomButtonEnableSlot);

    Square.insert(std::pair<QString,QGridSquare *>("B1",ui->B1));
    ui->B1->setToolTip("B1");
    ui->B1->GreenSquareClickedTracking = false;
    //QObject::connect(ui->B1, &QGridSquare::RandomButtonEnableSig, this, &FillGridWindow::RandomButtonEnableSlot);
    Square.insert(std::pair<QString,QGridSquare *>("B2",ui->B2));
    ui->B2->setToolTip("B2");
    ui->B2->GreenSquareClickedTracking = false;
    //QObject::connect(ui->B2, &QGridSquare::RandomButtonEnableSig, this, &FillGridWindow::RandomButtonEnableSlot);
    Square.insert(std::pair<QString,QGridSquare *>("B3",ui->B3));
    ui->B3->setToolTip("B3");
    ui->B3->GreenSquareClickedTracking = false;
    //QObject::connect(ui->B3, &QGridSquare::RandomButtonEnableSig, this, &FillGridWindow::RandomButtonEnableSlot);
    Square.insert(std::pair<QString,QGridSquare *>("B4",ui->B4));
    ui->B4->setToolTip("B4");
    ui->B4->GreenSquareClickedTracking = false;
    Square.insert(std::pair<QString,QGridSquare *>("B5",ui->B5));
    ui->B5->setToolTip("B5");
    ui->B5->GreenSquareClickedTracking = false;
    Square.insert(std::pair<QString,QGridSquare *>("B6",ui->B6));
    ui->B6->setToolTip("B6");
    ui->B6->GreenSquareClickedTracking = false;
    Square.insert(std::pair<QString,QGridSquare *>("B7",ui->B7));
    ui->B7->setToolTip("B7");
    ui->B7->GreenSquareClickedTracking = false;
    Square.insert(std::pair<QString,QGridSquare *>("B8",ui->B8));
    ui->B8->setToolTip("B8");
    ui->B8->GreenSquareClickedTracking = false;
    Square.insert(std::pair<QString,QGridSquare *>("B9",ui->B9));
    ui->B9->setToolTip("B9");
    ui->B9->GreenSquareClickedTracking = false;
    Square.insert(std::pair<QString,QGridSquare *>("B10",ui->B10));
    ui->B10->setToolTip("B10");
    ui->B10->GreenSquareClickedTracking = false;

    Square.insert(std::pair<QString,QGridSquare *>("C1",ui->C1));
    ui->C1->setToolTip("C1");
    ui->C1->GreenSquareClickedTracking = false;
    Square.insert(std::pair<QString,QGridSquare *>("C2",ui->C2));
    ui->C2->setToolTip("C2");
    ui->C2->GreenSquareClickedTracking = false;
    Square.insert(std::pair<QString,QGridSquare *>("C3",ui->C3));
    ui->C3->setToolTip("C3");
    ui->C3->GreenSquareClickedTracking = false;
    Square.insert(std::pair<QString,QGridSquare *>("C4",ui->C4));
    ui->C4->setToolTip("C4");
    ui->C4->GreenSquareClickedTracking = false;
    Square.insert(std::pair<QString,QGridSquare *>("C5",ui->C5));
    ui->C5->setToolTip("C5");
    ui->C5->GreenSquareClickedTracking = false;
    Square.insert(std::pair<QString,QGridSquare *>("C6",ui->C6));
    ui->C6->setToolTip("C6");
    ui->C6->GreenSquareClickedTracking = false;
    Square.insert(std::pair<QString,QGridSquare *>("C7",ui->C7));
    ui->C7->setToolTip("C7");
    ui->C7->GreenSquareClickedTracking = false;
    Square.insert(std::pair<QString,QGridSquare *>("C8",ui->C8));
    ui->C8->setToolTip("C8");
    ui->C8->GreenSquareClickedTracking = false;
    Square.insert(std::pair<QString,QGridSquare *>("C9",ui->C9));
    ui->C9->setToolTip("C9");
    ui->C9->GreenSquareClickedTracking = false;
    Square.insert(std::pair<QString,QGridSquare *>("C10",ui->C10));
    ui->C10->setToolTip("C10");
    ui->C10->GreenSquareClickedTracking = false;

    Square.insert(std::pair<QString,QGridSquare *>("D1",ui->D1));
    ui->D1->setToolTip("D1");
    ui->D1->GreenSquareClickedTracking = false;
    Square.insert(std::pair<QString,QGridSquare *>("D2",ui->D2));
    ui->D2->setToolTip("D2");
    ui->D2->GreenSquareClickedTracking = false;
    Square.insert(std::pair<QString,QGridSquare *>("D3",ui->D3));
    ui->D3->setToolTip("D3");
    ui->D3->GreenSquareClickedTracking = false;
    Square.insert(std::pair<QString,QGridSquare *>("D4",ui->D4));
    ui->D4->setToolTip("D4");
    ui->D4->GreenSquareClickedTracking = false;
    Square.insert(std::pair<QString,QGridSquare *>("D5",ui->D5));
    ui->D5->setToolTip("D5");
    ui->D5->GreenSquareClickedTracking = false;
    Square.insert(std::pair<QString,QGridSquare *>("D6",ui->D6));
    ui->D6->setToolTip("D6");
    ui->D6->GreenSquareClickedTracking = false;
    Square.insert(std::pair<QString,QGridSquare *>("D7",ui->D7));
    ui->D7->setToolTip("D7");
    ui->D7->GreenSquareClickedTracking = false;
    Square.insert(std::pair<QString,QGridSquare *>("D8",ui->D8));
    ui->D8->setToolTip("D8");
    ui->D8->GreenSquareClickedTracking = false;
    Square.insert(std::pair<QString,QGridSquare *>("D9",ui->D9));
    ui->D9->setToolTip("D9");
    ui->D9->GreenSquareClickedTracking = false;
    Square.insert(std::pair<QString,QGridSquare *>("D10",ui->D10));
    ui->D10->setToolTip("D10");
    ui->D10->GreenSquareClickedTracking = false;

    Square.insert(std::pair<QString,QGridSquare *>("E1",ui->E1));
    ui->E1->setToolTip("E1");
    ui->E1->GreenSquareClickedTracking = false;
    Square.insert(std::pair<QString,QGridSquare *>("E2",ui->E2));
    ui->E2->setToolTip("E2");
    ui->E2->GreenSquareClickedTracking = false;
    Square.insert(std::pair<QString,QGridSquare *>("E3",ui->E3));
    ui->E3->setToolTip("E3");
    ui->E3->GreenSquareClickedTracking = false;
    Square.insert(std::pair<QString,QGridSquare *>("E4",ui->E4));
    ui->E4->setToolTip("E4");
    ui->E4->GreenSquareClickedTracking = false;
    Square.insert(std::pair<QString,QGridSquare *>("E5",ui->E5));
    ui->E5->setToolTip("E5");
    ui->E5->GreenSquareClickedTracking = false;
    Square.insert(std::pair<QString,QGridSquare *>("E6",ui->E6));
    ui->E6->setToolTip("E6");
    ui->E6->GreenSquareClickedTracking = false;
    Square.insert(std::pair<QString,QGridSquare *>("E7",ui->E7));
    ui->E7->setToolTip("E7");
    ui->E7->GreenSquareClickedTracking = false;
    Square.insert(std::pair<QString,QGridSquare *>("E8",ui->E8));
    ui->E8->setToolTip("E8");
    ui->E8->GreenSquareClickedTracking = false;
    Square.insert(std::pair<QString,QGridSquare *>("E9",ui->E9));
    ui->E9->setToolTip("E9");
    ui->E9->GreenSquareClickedTracking = false;
    Square.insert(std::pair<QString,QGridSquare *>("E10",ui->E10));
    ui->E10->setToolTip("E10");
    ui->E10->GreenSquareClickedTracking = false;

    Square.insert(std::pair<QString,QGridSquare *>("F1",ui->F1));
    ui->F1->setToolTip("F1");
    ui->F1->GreenSquareClickedTracking = false;
    Square.insert(std::pair<QString,QGridSquare *>("F2",ui->F2));
    ui->F2->setToolTip("F2");
    ui->F2->GreenSquareClickedTracking = false;
    Square.insert(std::pair<QString,QGridSquare *>("F3",ui->F3));
    ui->F3->setToolTip("F3");
    ui->F3->GreenSquareClickedTracking = false;
    Square.insert(std::pair<QString,QGridSquare *>("F4",ui->F4));
    ui->F4->setToolTip("F4");
    ui->F4->GreenSquareClickedTracking = false;
    Square.insert(std::pair<QString,QGridSquare *>("F5",ui->F5));
    ui->F5->setToolTip("F5");
    ui->F5->GreenSquareClickedTracking = false;
    Square.insert(std::pair<QString,QGridSquare *>("F6",ui->F6));
    ui->F6->setToolTip("F6");
    ui->F6->GreenSquareClickedTracking = false;
    Square.insert(std::pair<QString,QGridSquare *>("F7",ui->F7));
    ui->F7->setToolTip("F7");
    ui->F7->GreenSquareClickedTracking = false;
    Square.insert(std::pair<QString,QGridSquare *>("F8",ui->F8));
    ui->F8->setToolTip("F8");
    ui->F8->GreenSquareClickedTracking = false;
    Square.insert(std::pair<QString,QGridSquare *>("F9",ui->F9));
    ui->F9->setToolTip("F9");
    ui->F9->GreenSquareClickedTracking = false;
    Square.insert(std::pair<QString,QGridSquare *>("F10",ui->F10));
    ui->F10->setToolTip("F10");
    ui->F10->GreenSquareClickedTracking = false;

    Square.insert(std::pair<QString,QGridSquare *>("G1",ui->G1));
    ui->G1->setToolTip("G1");
    ui->G1->GreenSquareClickedTracking = false;
    Square.insert(std::pair<QString,QGridSquare *>("G2",ui->G2));
    ui->G2->setToolTip("G2");
    ui->G2->GreenSquareClickedTracking = false;
    Square.insert(std::pair<QString,QGridSquare *>("G3",ui->G3));
    ui->G3->setToolTip("G3");
    ui->G3->GreenSquareClickedTracking = false;
    Square.insert(std::pair<QString,QGridSquare *>("G4",ui->G4));
    ui->G4->setToolTip("G4");
    ui->G4->GreenSquareClickedTracking = false;
    Square.insert(std::pair<QString,QGridSquare *>("G5",ui->G5));
    ui->G5->setToolTip("G5");
    ui->G5->GreenSquareClickedTracking = false;
    Square.insert(std::pair<QString,QGridSquare *>("G6",ui->G6));
    ui->G6->setToolTip("G6");
    ui->G6->GreenSquareClickedTracking = false;
    Square.insert(std::pair<QString,QGridSquare *>("G7",ui->G7));
    ui->G7->setToolTip("G7");
    ui->G7->GreenSquareClickedTracking = false;
    Square.insert(std::pair<QString,QGridSquare *>("G8",ui->G8));
    ui->G8->setToolTip("G8");
    ui->G8->GreenSquareClickedTracking = false;
    Square.insert(std::pair<QString,QGridSquare *>("G9",ui->G9));
    ui->G9->setToolTip("G9");
    ui->G9->GreenSquareClickedTracking = false;
    Square.insert(std::pair<QString,QGridSquare *>("G10",ui->G10));
    ui->G10->setToolTip("G10");
    ui->G10->GreenSquareClickedTracking = false;

    Square.insert(std::pair<QString,QGridSquare *>("H1",ui->H1));
    ui->H1->setToolTip("H1");
    ui->H1->GreenSquareClickedTracking = false;
    Square.insert(std::pair<QString,QGridSquare *>("H2",ui->H2));
    ui->H2->setToolTip("H2");
    ui->H2->GreenSquareClickedTracking = false;
    Square.insert(std::pair<QString,QGridSquare *>("H3",ui->H3));
    ui->H3->setToolTip("H3");
    ui->H3->GreenSquareClickedTracking = false;
    Square.insert(std::pair<QString,QGridSquare *>("H4",ui->H4));
    ui->H4->setToolTip("H4");
    ui->H4->GreenSquareClickedTracking = false;
    Square.insert(std::pair<QString,QGridSquare *>("H5",ui->H5));
    ui->H5->setToolTip("H5");
    ui->H5->GreenSquareClickedTracking = false;
    Square.insert(std::pair<QString,QGridSquare *>("H6",ui->H6));
    ui->H6->setToolTip("H6");
    ui->H6->GreenSquareClickedTracking = false;
    Square.insert(std::pair<QString,QGridSquare *>("H7",ui->H7));
    ui->H7->setToolTip("H7");
    ui->H7->GreenSquareClickedTracking = false;
    Square.insert(std::pair<QString,QGridSquare *>("H8",ui->H8));
    ui->H8->setToolTip("H8");
    ui->H8->GreenSquareClickedTracking = false;
    Square.insert(std::pair<QString,QGridSquare *>("H9",ui->H9));
    ui->H9->setToolTip("H9");
    ui->H9->GreenSquareClickedTracking = false;
    Square.insert(std::pair<QString,QGridSquare *>("H10",ui->H10));
    ui->H10->setToolTip("H10");
    ui->H10->GreenSquareClickedTracking = false;

    Square.insert(std::pair<QString,QGridSquare *>("I1",ui->I1));
    ui->I1->setToolTip("I1");
    ui->I1->GreenSquareClickedTracking = false;
    Square.insert(std::pair<QString,QGridSquare *>("I2",ui->I2));
    ui->I2->setToolTip("I2");
    ui->I2->GreenSquareClickedTracking = false;
    Square.insert(std::pair<QString,QGridSquare *>("I3",ui->I3));
    ui->I3->setToolTip("I3");
    ui->I3->GreenSquareClickedTracking = false;
    Square.insert(std::pair<QString,QGridSquare *>("I4",ui->I4));
    ui->I4->setToolTip("I4");
    ui->I4->GreenSquareClickedTracking = false;
    Square.insert(std::pair<QString,QGridSquare *>("I5",ui->I5));
    ui->I5->setToolTip("I5");
    ui->I5->GreenSquareClickedTracking = false;
    Square.insert(std::pair<QString,QGridSquare *>("I6",ui->I6));
    ui->I6->setToolTip("I6");
    ui->I6->GreenSquareClickedTracking = false;
    Square.insert(std::pair<QString,QGridSquare *>("I7",ui->I7));
    ui->I7->setToolTip("I7");
    ui->I7->GreenSquareClickedTracking = false;
    Square.insert(std::pair<QString,QGridSquare *>("I8",ui->I8));
    ui->I8->setToolTip("I8");
    ui->I8->GreenSquareClickedTracking = false;
    Square.insert(std::pair<QString,QGridSquare *>("I9",ui->I9));
    ui->I9->setToolTip("I9");
    ui->I9->GreenSquareClickedTracking = false;
    Square.insert(std::pair<QString,QGridSquare *>("I10",ui->I10));
    ui->I10->setToolTip("I10");
    ui->I10->GreenSquareClickedTracking = false;

    Square.insert(std::pair<QString,QGridSquare *>("J1",ui->J1));
    ui->J1->setToolTip("J1");
    ui->J1->GreenSquareClickedTracking = false;
    Square.insert(std::pair<QString,QGridSquare *>("J2",ui->J2));
    ui->J2->setToolTip("J2");
    ui->J2->GreenSquareClickedTracking = false;
    Square.insert(std::pair<QString,QGridSquare *>("J3",ui->J3));
    ui->J3->setToolTip("J3");
    ui->J3->GreenSquareClickedTracking = false;
    Square.insert(std::pair<QString,QGridSquare *>("J4",ui->J4));
    ui->J4->setToolTip("J4");
    ui->J4->GreenSquareClickedTracking = false;
    Square.insert(std::pair<QString,QGridSquare *>("J5",ui->J5));
    ui->J5->setToolTip("J5");
    ui->J5->GreenSquareClickedTracking = false;
    Square.insert(std::pair<QString,QGridSquare *>("J6",ui->J6));
    ui->J6->setToolTip("J6");
    ui->J6->GreenSquareClickedTracking = false;
    Square.insert(std::pair<QString,QGridSquare *>("J7",ui->J7));
    ui->J7->setToolTip("J7");
    ui->J7->GreenSquareClickedTracking = false;
    Square.insert(std::pair<QString,QGridSquare *>("J8",ui->J8));
    ui->J8->setToolTip("J8");
    ui->J8->GreenSquareClickedTracking = false;
    Square.insert(std::pair<QString,QGridSquare *>("J9",ui->J9));
    ui->J9->setToolTip("J9");
    ui->J9->GreenSquareClickedTracking = false;
    Square.insert(std::pair<QString,QGridSquare *>("J10",ui->J10));
    ui->J10->setToolTip("J10");
    ui->J10->GreenSquareClickedTracking = false;

    qDebug() << "All squares of the grid (Fill Grid Window) were associated with their coordinates in QString format";
}
