#include "server.h"
#include "ui_server.h"

void server::LinkCoordinatesAndActualSquares()
{
    RedPlayerGrid.insert(std::pair<QString, QGridSquare *>("A1",ui->RA1));
    ui->RA1->setToolTip("A1");
    RedPlayerGrid.insert(std::pair<QString, QGridSquare *>("A2",ui->RA2));
    ui->RA2->setToolTip("A2");
    RedPlayerGrid.insert(std::pair<QString, QGridSquare *>("A3",ui->RA3));
    ui->RA3->setToolTip("A3");
    RedPlayerGrid.insert(std::pair<QString, QGridSquare *>("A4",ui->RA4));
    ui->RA4->setToolTip("A4");
    RedPlayerGrid.insert(std::pair<QString, QGridSquare *>("A5",ui->RA5));
    ui->RA5->setToolTip("A5");
    RedPlayerGrid.insert(std::pair<QString, QGridSquare *>("A6",ui->RA6));
    ui->RA6->setToolTip("A6");
    RedPlayerGrid.insert(std::pair<QString, QGridSquare *>("A7",ui->RA7));
    ui->RA7->setToolTip("A7");
    RedPlayerGrid.insert(std::pair<QString, QGridSquare *>("A8",ui->RA8));
    ui->RA8->setToolTip("A8");
    RedPlayerGrid.insert(std::pair<QString, QGridSquare *>("A9",ui->RA9));
    ui->RA9->setToolTip("A9");
    RedPlayerGrid.insert(std::pair<QString, QGridSquare *>("A10",ui->RA10));
    ui->RA10->setToolTip("A10");

    RedPlayerGrid.insert(std::pair<QString, QGridSquare *>("B1",ui->RB1));
    ui->RB1->setToolTip("B1");
    RedPlayerGrid.insert(std::pair<QString, QGridSquare *>("B2",ui->RB2));
    ui->RB2->setToolTip("B2");
    RedPlayerGrid.insert(std::pair<QString, QGridSquare *>("B3",ui->RB3));
    ui->RB3->setToolTip("B3");
    RedPlayerGrid.insert(std::pair<QString, QGridSquare *>("B4",ui->RB4));
    ui->RB4->setToolTip("B4");
    RedPlayerGrid.insert(std::pair<QString, QGridSquare *>("B5",ui->RB5));
    ui->RB5->setToolTip("B5");
    RedPlayerGrid.insert(std::pair<QString, QGridSquare *>("B6",ui->RB6));
    ui->RB6->setToolTip("B6");
    RedPlayerGrid.insert(std::pair<QString, QGridSquare *>("B7",ui->RB7));
    ui->RB7->setToolTip("B7");
    RedPlayerGrid.insert(std::pair<QString, QGridSquare *>("B8",ui->RB8));
    ui->RB8->setToolTip("B8");
    RedPlayerGrid.insert(std::pair<QString, QGridSquare *>("B9",ui->RB9));
    ui->RB9->setToolTip("B9");
    RedPlayerGrid.insert(std::pair<QString, QGridSquare *>("B10",ui->RB10));
    ui->RB10->setToolTip("B10");

    RedPlayerGrid.insert(std::pair<QString, QGridSquare *>("C1",ui->RC1));
    ui->RC1->setToolTip("C1");
    RedPlayerGrid.insert(std::pair<QString, QGridSquare *>("C2",ui->RC2));
    ui->RC2->setToolTip("C2");
    RedPlayerGrid.insert(std::pair<QString, QGridSquare *>("C3",ui->RC3));
    ui->RC3->setToolTip("C3");
    RedPlayerGrid.insert(std::pair<QString, QGridSquare *>("C4",ui->RC4));
    ui->RC4->setToolTip("C4");
    RedPlayerGrid.insert(std::pair<QString, QGridSquare *>("C5",ui->RC5));
    ui->RC5->setToolTip("C5");
    RedPlayerGrid.insert(std::pair<QString, QGridSquare *>("C6",ui->RC6));
    ui->RC6->setToolTip("C6");
    RedPlayerGrid.insert(std::pair<QString, QGridSquare *>("C7",ui->RC7));
    ui->RC7->setToolTip("C7");
    RedPlayerGrid.insert(std::pair<QString, QGridSquare *>("C8",ui->RC8));
    ui->RC8->setToolTip("C8");
    RedPlayerGrid.insert(std::pair<QString, QGridSquare *>("C9",ui->RC9));
    ui->RC9->setToolTip("C9");
    RedPlayerGrid.insert(std::pair<QString, QGridSquare *>("C10",ui->RC10));
    ui->RC10->setToolTip("C10");

    RedPlayerGrid.insert(std::pair<QString, QGridSquare *>("D1",ui->RD1));
    ui->RD1->setToolTip("D1");
    RedPlayerGrid.insert(std::pair<QString, QGridSquare *>("D2",ui->RD2));
    ui->RD2->setToolTip("D2");
    RedPlayerGrid.insert(std::pair<QString, QGridSquare *>("D3",ui->RD3));
    ui->RD3->setToolTip("D3");
    RedPlayerGrid.insert(std::pair<QString, QGridSquare *>("D4",ui->RD4));
    ui->RD4->setToolTip("D4");
    RedPlayerGrid.insert(std::pair<QString, QGridSquare *>("D5",ui->RD5));
    ui->RD5->setToolTip("D5");
    RedPlayerGrid.insert(std::pair<QString, QGridSquare *>("D6",ui->RD6));
    ui->RD6->setToolTip("D6");
    RedPlayerGrid.insert(std::pair<QString, QGridSquare *>("D7",ui->RD7));
    ui->RD7->setToolTip("D7");
    RedPlayerGrid.insert(std::pair<QString, QGridSquare *>("D8",ui->RD8));
    ui->RD8->setToolTip("D8");
    RedPlayerGrid.insert(std::pair<QString, QGridSquare *>("D9",ui->RD9));
    ui->RD9->setToolTip("D9");
    RedPlayerGrid.insert(std::pair<QString, QGridSquare *>("D10",ui->RD10));
    ui->RD10->setToolTip("D10");

    RedPlayerGrid.insert(std::pair<QString, QGridSquare *>("E1",ui->RE1));
    ui->RE1->setToolTip("E1");
    RedPlayerGrid.insert(std::pair<QString, QGridSquare *>("E2",ui->RE2));
    ui->RE2->setToolTip("E2");
    RedPlayerGrid.insert(std::pair<QString, QGridSquare *>("E3",ui->RE3));
    ui->RE3->setToolTip("E3");
    RedPlayerGrid.insert(std::pair<QString, QGridSquare *>("E4",ui->RE4));
    ui->RE4->setToolTip("E4");
    RedPlayerGrid.insert(std::pair<QString, QGridSquare *>("E5",ui->RE5));
    ui->RE5->setToolTip("E5");
    RedPlayerGrid.insert(std::pair<QString, QGridSquare *>("E6",ui->RE6));
    ui->RE6->setToolTip("E6");
    RedPlayerGrid.insert(std::pair<QString, QGridSquare *>("E7",ui->RE7));
    ui->RE7->setToolTip("E7");
    RedPlayerGrid.insert(std::pair<QString, QGridSquare *>("E8",ui->RE8));
    ui->RE8->setToolTip("E8");
    RedPlayerGrid.insert(std::pair<QString, QGridSquare *>("E9",ui->RE9));
    ui->RE9->setToolTip("E9");
    RedPlayerGrid.insert(std::pair<QString, QGridSquare *>("E10",ui->RE10));
    ui->RE10->setToolTip("E10");

    RedPlayerGrid.insert(std::pair<QString, QGridSquare *>("F1",ui->RF1));
    ui->RF1->setToolTip("F1");
    RedPlayerGrid.insert(std::pair<QString, QGridSquare *>("F2",ui->RF2));
    ui->RF2->setToolTip("F2");
    RedPlayerGrid.insert(std::pair<QString, QGridSquare *>("F3",ui->RF3));
    ui->RF3->setToolTip("F3");
    RedPlayerGrid.insert(std::pair<QString, QGridSquare *>("F4",ui->RF4));
    ui->RF4->setToolTip("F4");
    RedPlayerGrid.insert(std::pair<QString, QGridSquare *>("F5",ui->RF5));
    ui->RF5->setToolTip("F5");
    RedPlayerGrid.insert(std::pair<QString, QGridSquare *>("F6",ui->RF6));
    ui->RF6->setToolTip("F6");
    RedPlayerGrid.insert(std::pair<QString, QGridSquare *>("F7",ui->RF7));
    ui->RF7->setToolTip("F7");
    RedPlayerGrid.insert(std::pair<QString, QGridSquare *>("F8",ui->RF8));
    ui->RF8->setToolTip("F8");
    RedPlayerGrid.insert(std::pair<QString, QGridSquare *>("F9",ui->RF9));
    ui->RF9->setToolTip("F9");
    RedPlayerGrid.insert(std::pair<QString, QGridSquare *>("F10",ui->RF10));
    ui->RF10->setToolTip("F10");

    RedPlayerGrid.insert(std::pair<QString, QGridSquare *>("G1",ui->RG1));
    ui->RG1->setToolTip("G1");
    RedPlayerGrid.insert(std::pair<QString, QGridSquare *>("G2",ui->RG2));
    ui->RG2->setToolTip("G2");
    RedPlayerGrid.insert(std::pair<QString, QGridSquare *>("G3",ui->RG3));
    ui->RG3->setToolTip("G3");
    RedPlayerGrid.insert(std::pair<QString, QGridSquare *>("G4",ui->RG4));
    ui->RG4->setToolTip("G4");
    RedPlayerGrid.insert(std::pair<QString, QGridSquare *>("G5",ui->RG5));
    ui->RG5->setToolTip("G5");
    RedPlayerGrid.insert(std::pair<QString, QGridSquare *>("G6",ui->RG6));
    ui->RG6->setToolTip("G6");
    RedPlayerGrid.insert(std::pair<QString, QGridSquare *>("G7",ui->RG7));
    ui->RG7->setToolTip("G7");
    RedPlayerGrid.insert(std::pair<QString, QGridSquare *>("G8",ui->RG8));
    ui->RG8->setToolTip("G8");
    RedPlayerGrid.insert(std::pair<QString, QGridSquare *>("G9",ui->RG9));
    ui->RG9->setToolTip("G9");
    RedPlayerGrid.insert(std::pair<QString, QGridSquare *>("G10",ui->RG10));
    ui->RG10->setToolTip("G10");

    RedPlayerGrid.insert(std::pair<QString, QGridSquare *>("H1",ui->RH1));
    ui->RH1->setToolTip("H1");
    RedPlayerGrid.insert(std::pair<QString, QGridSquare *>("H2",ui->RH2));
    ui->RH2->setToolTip("H2");
    RedPlayerGrid.insert(std::pair<QString, QGridSquare *>("H3",ui->RH3));
    ui->RH3->setToolTip("H3");
    RedPlayerGrid.insert(std::pair<QString, QGridSquare *>("H4",ui->RH4));
    ui->RH4->setToolTip("H4");
    RedPlayerGrid.insert(std::pair<QString, QGridSquare *>("H5",ui->RH5));
    ui->RH5->setToolTip("H5");
    RedPlayerGrid.insert(std::pair<QString, QGridSquare *>("H6",ui->RH6));
    ui->RH6->setToolTip("H6");
    RedPlayerGrid.insert(std::pair<QString, QGridSquare *>("H7",ui->RH7));
    ui->RH7->setToolTip("H7");
    RedPlayerGrid.insert(std::pair<QString, QGridSquare *>("H8",ui->RH8));
    ui->RH8->setToolTip("H8");
    RedPlayerGrid.insert(std::pair<QString, QGridSquare *>("H9",ui->RH9));
    ui->RH9->setToolTip("H9");
    RedPlayerGrid.insert(std::pair<QString, QGridSquare *>("H10",ui->RH10));
    ui->RH10->setToolTip("H10");

    RedPlayerGrid.insert(std::pair<QString, QGridSquare *>("I1",ui->RI1));
    ui->RI1->setToolTip("I1");
    RedPlayerGrid.insert(std::pair<QString, QGridSquare *>("I2",ui->RI2));
    ui->RI2->setToolTip("I2");
    RedPlayerGrid.insert(std::pair<QString, QGridSquare *>("I3",ui->RI3));
    ui->RI3->setToolTip("I3");
    RedPlayerGrid.insert(std::pair<QString, QGridSquare *>("I4",ui->RI4));
    ui->RI4->setToolTip("I4");
    RedPlayerGrid.insert(std::pair<QString, QGridSquare *>("I5",ui->RI5));
    ui->RI5->setToolTip("I5");
    RedPlayerGrid.insert(std::pair<QString, QGridSquare *>("I6",ui->RI6));
    ui->RI6->setToolTip("I6");
    RedPlayerGrid.insert(std::pair<QString, QGridSquare *>("I7",ui->RI7));
    ui->RI7->setToolTip("I7");
    RedPlayerGrid.insert(std::pair<QString, QGridSquare *>("I8",ui->RI8));
    ui->RI8->setToolTip("I8");
    RedPlayerGrid.insert(std::pair<QString, QGridSquare *>("I9",ui->RI9));
    ui->RI9->setToolTip("I9");
    RedPlayerGrid.insert(std::pair<QString, QGridSquare *>("I10",ui->RI10));
    ui->RI10->setToolTip("I10");

    RedPlayerGrid.insert(std::pair<QString, QGridSquare *>("J1",ui->RJ1));
    ui->RJ1->setToolTip("J1");
    RedPlayerGrid.insert(std::pair<QString, QGridSquare *>("J2",ui->RJ2));
    ui->RJ2->setToolTip("J2");
    RedPlayerGrid.insert(std::pair<QString, QGridSquare *>("J3",ui->RJ3));
    ui->RJ3->setToolTip("J3");
    RedPlayerGrid.insert(std::pair<QString, QGridSquare *>("J4",ui->RJ4));
    ui->RJ4->setToolTip("J4");
    RedPlayerGrid.insert(std::pair<QString, QGridSquare *>("J5",ui->RJ5));
    ui->RJ5->setToolTip("J5");
    RedPlayerGrid.insert(std::pair<QString, QGridSquare *>("J6",ui->RJ6));
    ui->RJ6->setToolTip("J6");
    RedPlayerGrid.insert(std::pair<QString, QGridSquare *>("J7",ui->RJ7));
    ui->RJ7->setToolTip("J7");
    RedPlayerGrid.insert(std::pair<QString, QGridSquare *>("J8",ui->RJ8));
    ui->RJ8->setToolTip("J8");
    RedPlayerGrid.insert(std::pair<QString, QGridSquare *>("J9",ui->RJ9));
    ui->RJ9->setToolTip("J9");
    RedPlayerGrid.insert(std::pair<QString, QGridSquare *>("J10",ui->RJ10));
    ui->RJ10->setToolTip("J10");

    BluePlayerGrid.insert(std::pair<QString, QGridSquare *>("A1",ui->BA1));
    ui->BA1->setToolTip("A1");
    BluePlayerGrid.insert(std::pair<QString, QGridSquare *>("A2",ui->BA2));
    ui->BA2->setToolTip("A2");
    BluePlayerGrid.insert(std::pair<QString, QGridSquare *>("A3",ui->BA3));
    ui->BA3->setToolTip("A3");
    BluePlayerGrid.insert(std::pair<QString, QGridSquare *>("A4",ui->BA4));
    ui->BA4->setToolTip("A4");
    BluePlayerGrid.insert(std::pair<QString, QGridSquare *>("A5",ui->BA5));
    ui->BA5->setToolTip("A5");
    BluePlayerGrid.insert(std::pair<QString, QGridSquare *>("A6",ui->BA6));
    ui->BA6->setToolTip("A6");
    BluePlayerGrid.insert(std::pair<QString, QGridSquare *>("A7",ui->BA7));
    ui->BA7->setToolTip("A7");
    BluePlayerGrid.insert(std::pair<QString, QGridSquare *>("A8",ui->BA8));
    ui->BA8->setToolTip("A8");
    BluePlayerGrid.insert(std::pair<QString, QGridSquare *>("A9",ui->BA9));
    ui->BA9->setToolTip("A9");
    BluePlayerGrid.insert(std::pair<QString, QGridSquare *>("A10",ui->BA10));
    ui->BA10->setToolTip("A10");

    BluePlayerGrid.insert(std::pair<QString, QGridSquare *>("B1",ui->BB1));
    ui->BB1->setToolTip("B1");
    BluePlayerGrid.insert(std::pair<QString, QGridSquare *>("B2",ui->BB2));
    ui->BB2->setToolTip("B2");
    BluePlayerGrid.insert(std::pair<QString, QGridSquare *>("B3",ui->BB3));
    ui->BB3->setToolTip("B3");
    BluePlayerGrid.insert(std::pair<QString, QGridSquare *>("B4",ui->BB4));
    ui->BB4->setToolTip("B4");
    BluePlayerGrid.insert(std::pair<QString, QGridSquare *>("B5",ui->BB5));
    ui->BB5->setToolTip("B5");
    BluePlayerGrid.insert(std::pair<QString, QGridSquare *>("B6",ui->BB6));
    ui->BB6->setToolTip("B6");
    BluePlayerGrid.insert(std::pair<QString, QGridSquare *>("B7",ui->BB7));
    ui->BB7->setToolTip("B7");
    BluePlayerGrid.insert(std::pair<QString, QGridSquare *>("B8",ui->BB8));
    ui->BB8->setToolTip("B8");
    BluePlayerGrid.insert(std::pair<QString, QGridSquare *>("B9",ui->BB9));
    ui->BB9->setToolTip("B9");
    BluePlayerGrid.insert(std::pair<QString, QGridSquare *>("B10",ui->BB10));
    ui->BB10->setToolTip("B10");

    BluePlayerGrid.insert(std::pair<QString, QGridSquare *>("C1",ui->BC1));
    ui->BC1->setToolTip("C1");
    BluePlayerGrid.insert(std::pair<QString, QGridSquare *>("C2",ui->BC2));
    ui->BC2->setToolTip("C2");
    BluePlayerGrid.insert(std::pair<QString, QGridSquare *>("C3",ui->BC3));
    ui->BC3->setToolTip("C3");
    BluePlayerGrid.insert(std::pair<QString, QGridSquare *>("C4",ui->BC4));
    ui->BC4->setToolTip("C4");
    BluePlayerGrid.insert(std::pair<QString, QGridSquare *>("C5",ui->BC5));
    ui->BC5->setToolTip("C5");
    BluePlayerGrid.insert(std::pair<QString, QGridSquare *>("C6",ui->BC6));
    ui->BC6->setToolTip("C6");
    BluePlayerGrid.insert(std::pair<QString, QGridSquare *>("C7",ui->BC7));
    ui->BC7->setToolTip("C7");
    BluePlayerGrid.insert(std::pair<QString, QGridSquare *>("C8",ui->BC8));
    ui->BC8->setToolTip("C8");
    BluePlayerGrid.insert(std::pair<QString, QGridSquare *>("C9",ui->BC9));
    ui->BC9->setToolTip("C9");
    BluePlayerGrid.insert(std::pair<QString, QGridSquare *>("C10",ui->BC10));
    ui->BC10->setToolTip("C10");

    BluePlayerGrid.insert(std::pair<QString, QGridSquare *>("D1",ui->BD1));
    ui->BD1->setToolTip("D1");
    BluePlayerGrid.insert(std::pair<QString, QGridSquare *>("D2",ui->BD2));
    ui->BD2->setToolTip("D2");
    BluePlayerGrid.insert(std::pair<QString, QGridSquare *>("D3",ui->BD3));
    ui->BD3->setToolTip("D3");
    BluePlayerGrid.insert(std::pair<QString, QGridSquare *>("D4",ui->BD4));
    ui->BD4->setToolTip("D4");
    BluePlayerGrid.insert(std::pair<QString, QGridSquare *>("D5",ui->BD5));
    ui->BD5->setToolTip("D5");
    BluePlayerGrid.insert(std::pair<QString, QGridSquare *>("D6",ui->BD6));
    ui->BD6->setToolTip("D6");
    BluePlayerGrid.insert(std::pair<QString, QGridSquare *>("D7",ui->BD7));
    ui->BD7->setToolTip("D7");
    BluePlayerGrid.insert(std::pair<QString, QGridSquare *>("D8",ui->BD8));
    ui->BD8->setToolTip("D8");
    BluePlayerGrid.insert(std::pair<QString, QGridSquare *>("D9",ui->BD9));
    ui->BD9->setToolTip("D9");
    BluePlayerGrid.insert(std::pair<QString, QGridSquare *>("D10",ui->BD10));
    ui->BD10->setToolTip("D10");

    BluePlayerGrid.insert(std::pair<QString, QGridSquare *>("E1",ui->BE1));
    ui->BE1->setToolTip("E1");
    BluePlayerGrid.insert(std::pair<QString, QGridSquare *>("E2",ui->BE2));
    ui->BE2->setToolTip("E2");
    BluePlayerGrid.insert(std::pair<QString, QGridSquare *>("E3",ui->BE3));
    ui->BE3->setToolTip("E3");
    BluePlayerGrid.insert(std::pair<QString, QGridSquare *>("E4",ui->BE4));
    ui->BE4->setToolTip("E4");
    BluePlayerGrid.insert(std::pair<QString, QGridSquare *>("E5",ui->BE5));
    ui->BE5->setToolTip("E5");
    BluePlayerGrid.insert(std::pair<QString, QGridSquare *>("E6",ui->BE6));
    ui->BE6->setToolTip("E6");
    BluePlayerGrid.insert(std::pair<QString, QGridSquare *>("E7",ui->BE7));
    ui->BE7->setToolTip("E7");
    BluePlayerGrid.insert(std::pair<QString, QGridSquare *>("E8",ui->BE8));
    ui->BE8->setToolTip("E8");
    BluePlayerGrid.insert(std::pair<QString, QGridSquare *>("E9",ui->BE9));
    ui->BE9->setToolTip("E9");
    BluePlayerGrid.insert(std::pair<QString, QGridSquare *>("E10",ui->BE10));
    ui->BE10->setToolTip("E10");

    BluePlayerGrid.insert(std::pair<QString, QGridSquare *>("F1",ui->BF1));
    ui->BF1->setToolTip("F1");
    BluePlayerGrid.insert(std::pair<QString, QGridSquare *>("F2",ui->BF2));
    ui->BF2->setToolTip("F2");
    BluePlayerGrid.insert(std::pair<QString, QGridSquare *>("F3",ui->BF3));
    ui->BF3->setToolTip("F3");
    BluePlayerGrid.insert(std::pair<QString, QGridSquare *>("F4",ui->BF4));
    ui->BF4->setToolTip("F4");
    BluePlayerGrid.insert(std::pair<QString, QGridSquare *>("F5",ui->BF5));
    ui->BF5->setToolTip("F5");
    BluePlayerGrid.insert(std::pair<QString, QGridSquare *>("F6",ui->BF6));
    ui->BF6->setToolTip("F6");
    BluePlayerGrid.insert(std::pair<QString, QGridSquare *>("F7",ui->BF7));
    ui->BF7->setToolTip("F7");
    BluePlayerGrid.insert(std::pair<QString, QGridSquare *>("F8",ui->BF8));
    ui->BF8->setToolTip("F8");
    BluePlayerGrid.insert(std::pair<QString, QGridSquare *>("F9",ui->BF9));
    ui->BF9->setToolTip("F9");
    BluePlayerGrid.insert(std::pair<QString, QGridSquare *>("F10",ui->BF10));
    ui->BF10->setToolTip("F10");

    BluePlayerGrid.insert(std::pair<QString, QGridSquare *>("G1",ui->BG1));
    ui->BG1->setToolTip("G1");
    BluePlayerGrid.insert(std::pair<QString, QGridSquare *>("G2",ui->BG2));
    ui->BG2->setToolTip("G2");
    BluePlayerGrid.insert(std::pair<QString, QGridSquare *>("G3",ui->BG3));
    ui->BG3->setToolTip("G3");
    BluePlayerGrid.insert(std::pair<QString, QGridSquare *>("G4",ui->BG4));
    ui->BG4->setToolTip("G4");
    BluePlayerGrid.insert(std::pair<QString, QGridSquare *>("G5",ui->BG5));
    ui->BG5->setToolTip("G5");
    BluePlayerGrid.insert(std::pair<QString, QGridSquare *>("G6",ui->BG6));
    ui->BG6->setToolTip("G6");
    BluePlayerGrid.insert(std::pair<QString, QGridSquare *>("G7",ui->BG7));
    ui->BG7->setToolTip("G7");
    BluePlayerGrid.insert(std::pair<QString, QGridSquare *>("G8",ui->BG8));
    ui->BG8->setToolTip("G8");
    BluePlayerGrid.insert(std::pair<QString, QGridSquare *>("G9",ui->BG9));
    ui->BG9->setToolTip("G9");
    BluePlayerGrid.insert(std::pair<QString, QGridSquare *>("G10",ui->BG10));
    ui->BG10->setToolTip("G10");

    BluePlayerGrid.insert(std::pair<QString, QGridSquare *>("H1",ui->BH1));
    ui->BH1->setToolTip("H1");
    BluePlayerGrid.insert(std::pair<QString, QGridSquare *>("H2",ui->BH2));
    ui->BH2->setToolTip("H2");
    BluePlayerGrid.insert(std::pair<QString, QGridSquare *>("H3",ui->BH3));
    ui->BH3->setToolTip("H3");
    BluePlayerGrid.insert(std::pair<QString, QGridSquare *>("H4",ui->BH4));
    ui->BH4->setToolTip("H4");
    BluePlayerGrid.insert(std::pair<QString, QGridSquare *>("H5",ui->BH5));
    ui->BH5->setToolTip("H5");
    BluePlayerGrid.insert(std::pair<QString, QGridSquare *>("H6",ui->BH6));
    ui->BH6->setToolTip("H6");
    BluePlayerGrid.insert(std::pair<QString, QGridSquare *>("H7",ui->BH7));
    ui->BH7->setToolTip("H7");
    BluePlayerGrid.insert(std::pair<QString, QGridSquare *>("H8",ui->BH8));
    ui->BH8->setToolTip("H8");
    BluePlayerGrid.insert(std::pair<QString, QGridSquare *>("H9",ui->BH9));
    ui->BH9->setToolTip("H9");
    BluePlayerGrid.insert(std::pair<QString, QGridSquare *>("H10",ui->BH10));
    ui->BH10->setToolTip("H10");

    BluePlayerGrid.insert(std::pair<QString, QGridSquare *>("I1",ui->BI1));
    ui->BI1->setToolTip("I1");
    BluePlayerGrid.insert(std::pair<QString, QGridSquare *>("I2",ui->BI2));
    ui->BI2->setToolTip("I2");
    BluePlayerGrid.insert(std::pair<QString, QGridSquare *>("I3",ui->BI3));
    ui->BI3->setToolTip("I3");
    BluePlayerGrid.insert(std::pair<QString, QGridSquare *>("I4",ui->BI4));
    ui->BI4->setToolTip("I4");
    BluePlayerGrid.insert(std::pair<QString, QGridSquare *>("I5",ui->BI5));
    ui->BI5->setToolTip("I5");
    BluePlayerGrid.insert(std::pair<QString, QGridSquare *>("I6",ui->BI6));
    ui->BI6->setToolTip("I6");
    BluePlayerGrid.insert(std::pair<QString, QGridSquare *>("I7",ui->BI7));
    ui->BI7->setToolTip("I7");
    BluePlayerGrid.insert(std::pair<QString, QGridSquare *>("I8",ui->BI8));
    ui->BI8->setToolTip("I8");
    BluePlayerGrid.insert(std::pair<QString, QGridSquare *>("I9",ui->BI9));
    ui->BI9->setToolTip("I9");
    BluePlayerGrid.insert(std::pair<QString, QGridSquare *>("I10",ui->BI10));
    ui->BI10->setToolTip("I10");

    BluePlayerGrid.insert(std::pair<QString, QGridSquare *>("J1",ui->BJ1));
    ui->BJ1->setToolTip("J1");
    BluePlayerGrid.insert(std::pair<QString, QGridSquare *>("J2",ui->BJ2));
    ui->BJ2->setToolTip("J2");
    BluePlayerGrid.insert(std::pair<QString, QGridSquare *>("J3",ui->BJ3));
    ui->BJ3->setToolTip("J3");
    BluePlayerGrid.insert(std::pair<QString, QGridSquare *>("J4",ui->BJ4));
    ui->BJ4->setToolTip("J4");
    BluePlayerGrid.insert(std::pair<QString, QGridSquare *>("J5",ui->BJ5));
    ui->BJ5->setToolTip("J5");
    BluePlayerGrid.insert(std::pair<QString, QGridSquare *>("J6",ui->BJ6));
    ui->BJ6->setToolTip("J6");
    BluePlayerGrid.insert(std::pair<QString, QGridSquare *>("J7",ui->BJ7));
    ui->BJ7->setToolTip("J7");
    BluePlayerGrid.insert(std::pair<QString, QGridSquare *>("J8",ui->BJ8));
    ui->BJ8->setToolTip("J8");
    BluePlayerGrid.insert(std::pair<QString, QGridSquare *>("J9",ui->BJ9));
    ui->BJ9->setToolTip("J9");
    BluePlayerGrid.insert(std::pair<QString, QGridSquare *>("J10",ui->BJ10));
    ui->BJ10->setToolTip("J10");

}
